# This file was generated by GoReleaser. DO NOT EDIT.
cask "graphene" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "9b87d951cb853f6fd56ed256d9e3871b0837db72e95440c44d2a49adad94196b"
      url "https://github.com/aitorvs/graphene-releases/releases/download/v#{version}/gt-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "c2e7f33bcf1e1738dc5c0ee634605d72537e090558f1832c3395db15315fed1a"
      url "https://github.com/aitorvs/graphene-releases/releases/download/v#{version}/gt-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bca8f95bd4c677e648fe4a81a5a8836584cbe0260ee66d886d29807c17cb4c0e"
      url "https://github.com/aitorvs/graphene-releases/releases/download/v#{version}/gt-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "705ad7d4498e9998ab0e1612c6dafc33fd885cd06ccf0830347dfbdcf8607d7a"
      url "https://github.com/aitorvs/graphene-releases/releases/download/v#{version}/gt-linux-amd64.tar.gz"
    end
  end

  name "graphene"
  desc "Stacked pull requests for git and GitHub"
  homepage "https://github.com/aitorvs/graphene-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gt"]
    end
  end

  # No zap stanza required
end
