# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graphene < Formula
  desc "Stacked pull requests for git and GitHub"
  homepage "https://github.com/aitorvs/graphene-releases"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aitorvs/graphene-releases/releases/download/v0.1.0/gt-darwin-amd64.tar.gz"
      sha256 "9f9a89b940aacbbf2afe1018f82fd2f090fd1e336a5a1129f8900ae6108c7aa5"

      define_method(:install) do
        bin.install "gt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aitorvs/graphene-releases/releases/download/v0.1.0/gt-darwin-arm64.tar.gz"
      sha256 "aa58a99f9f36c437c70a3e28007b165347896d5b759d3096dd62a7bf790fc8b4"

      define_method(:install) do
        bin.install "gt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aitorvs/graphene-releases/releases/download/v0.1.0/gt-linux-amd64.tar.gz"
      sha256 "c0dbbd7b8444caeb9345efb01b7c043e3046827293452523dfc7ce9f6665336d"
      define_method(:install) do
        bin.install "gt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aitorvs/graphene-releases/releases/download/v0.1.0/gt-linux-arm64.tar.gz"
      sha256 "0ee340fd80786f9a0d42695b147d1d0047f79d0159cacc836be766f7b401aa1e"
      define_method(:install) do
        bin.install "gt"
      end
    end
  end

  test do
    system "#{bin}/gt", "--version"
  end
end
